"use client";
import {FormEvent,useEffect,useState} from "react";
import Dashboard from "./Dashboard";
import Workbench from "./Workbench";
import CmdbModule from "./cmdb/CmdbModule";
import {modules} from "./data";
import {APP_VERSION} from "./version";
function Login({onLogin}:{onLogin:()=>void}){const[account,setAccount]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");async function submit(e:FormEvent){e.preventDefault();const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({account,password})});if(r.ok)onLogin();else setError("账号或密码错误")}return <main className="login-page"><div className="orb a"/><div className="orb b"/><section className="login-card"><div className="brand-mark">∞</div><h1>北控伟仕智能运维平台</h1><p>编排混沌 · 智驭运维</p><form onSubmit={submit}><label>账号</label><div className="input-wrap"><span>♙</span><input aria-label="账号" placeholder="请输入账号" value={account} onChange={e=>setAccount(e.target.value)}/></div><label>密码</label><div className="input-wrap"><span>⌾</span><input aria-label="密码" type="password" placeholder="请输入密码" value={password} onChange={e=>setPassword(e.target.value)}/></div>{error&&<small className="error">{error}</small>}<button className="login-btn">登录系统</button><button type="button" className="reset-btn" onClick={()=>{setAccount("");setPassword("");setError("")}}>重置表单</button></form></section></main>}
export default function AutoOps(){const[authed,setAuthed]=useState<boolean|null>(null);const[moduleIndex,setModuleIndex]=useState(0);const[page,setPage]=useState("项目资产");const[nav,setNav]=useState(false);const[profile,setProfile]=useState(false);const[showCockpit,setShowCockpit]=useState(false);useEffect(()=>{fetch("/api/auth/session").then(r=>setAuthed(r.ok)).catch(()=>setAuthed(false))},[]);if(authed===null)return <div className="boot">北控伟仕智能运维平台</div>;if(!authed)return <Login onLogin={()=>setAuthed(true)}/>;const mod=modules[moduleIndex];function chooseModule(i:number){setModuleIndex(i);setPage(modules[i].menus[0]);setNav(false);setShowCockpit(false)}return <div className="shell"><header className="topbar"><div className="logo"><b>∞</b><strong>北控伟仕智能运维平台</strong></div><button className="nav-pill" onClick={()=>setNav(!nav)}>平台导航⌄</button><div className="account"><div className="version-pill" title={`北控伟仕智能运维平台 v${APP_VERSION}\n版本规则：修复Bug加末位，增加模块加中位，增加主菜单改首位`}><span className="version-dot"/><span style={{fontWeight:700,letterSpacing:"0.5px"}}>v{APP_VERSION}</span></div><button aria-label="切换驾驶舱" title={showCockpit?"返回资产管理":"打开全景驾驶舱大屏"} onClick={()=>setShowCockpit(!showCockpit)} style={{background:showCockpit?"#2563eb":"transparent",color:showCockpit?"#fff":"inherit",borderRadius:6,padding:"4px 8px",border:"1px solid #dce3eb",cursor:"pointer",display:"flex",alignItems:"center",gap:4,fontSize:12}}>▣ {showCockpit?"返回资产系统":"天枢驾驶舱"}</button><i>🐱</i><button className="account-btn" onClick={()=>setProfile(!profile)}>admin⌄</button>{profile&&<div className="profile-menu"><b>管理员</b><span>admin</span><button onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});setAuthed(false)}}>退出登录</button></div>}</div></header><aside className="sidebar"><h3>{mod.icon}　{mod.name}</h3>{mod.menus.map((x,i)=><button key={x} className={page===x&&!showCockpit?"active":""} onClick={()=>{setPage(x);setShowCockpit(false)}}><span>{["▣","♙","▰","♧","▥","◉","▢","◔","◌","⬡"][i]}</span>{x}</button>)}<button className="collapse">☷</button></aside>{showCockpit?<Dashboard/>:moduleIndex===0?<CmdbModule page={page} onPageChange={p=>setPage(p)}/>:<Workbench moduleName={mod.name} page={page}/>}

{nav&&<><button aria-label="关闭导航" className="nav-backdrop" onClick={()=>setNav(false)}/><section className="mega-nav"><header><div><b>平台导航</b><span>快速切换业务模块</span></div><button onClick={()=>setNav(false)}>×</button></header><div>{modules.map((m,i)=><button key={m.name} className={i===moduleIndex?"selected":""} onClick={()=>chooseModule(i)}><i>{m.icon}</i><span><b>{m.name}</b><small>{m.menus.length} 个菜单入口</small></span><em>›</em></button>)}</div></section></>}</div>}
