"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {descriptions,seedRows} from "./data";
type Row={id:number;name:string;display:string;category:string;owner:string;status:boolean;updated:string};
export default function Workbench({moduleName,page}:{moduleName:string;page:string}){
 const[query,setQuery]=useState("");const[status,setStatus]=useState("全部");const[rows,setRows]=useState<Row[]>(seedRows);const[modal,setModal]=useState(false);const[name,setName]=useState("");const[display,setDisplay]=useState("");
 useEffect(()=>{fetch("/api/records").then(r=>r.ok?r.json():null).then(d=>d?.rows&&setRows(d.rows)).catch(()=>{})},[]);
 const shown=useMemo(()=>rows.filter(r=>(!query||r.name.includes(query)||r.display.includes(query))&&(status==="全部"||r.status===(status==="启用"))),[rows,query,status]);
 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;const body={name,display:display||name,category:moduleName,owner:"admin",status:true};const r=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setRows(x=>[...x,d.row]);setModal(false);setName("");setDisplay("")}
 async function remove(id:number){await fetch("/api/records?id="+id,{method:"DELETE"});setRows(x=>x.filter(r=>r.id!==id))}
 async function toggle(row:Row){const next={...row,status:!row.status};await fetch("/api/records",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});setRows(x=>x.map(r=>r.id===row.id?next:r))}
 return <main className="workspace"><section className="page-title"><div className="page-icon">♙</div><div><h1>{page}</h1><p>{descriptions[page]||`集中管理${page}相关配置、状态与运行信息。`}</p></div><aside><span>{moduleName}</span><b>{rows.length}</b><span>记录</span><b>{shown.length}</b></aside></section>
 <section className="work-layout"><aside className="org-panel"><header><div><h3>组织架构</h3><small>DEPARTMENT</small></div><b>1<small>DEPTS</small></b></header><input placeholder="搜索部门..."/><div className="tree">▾　📁 神州科技有限公司<br/><span>　▾　▦ 深圳研发中心</span><br/><span>　　　• 运维部</span><br/><span>　　　• 研发部</span></div></aside>
 <section className="table-panel"><div className="filters"><label>关键字<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`请输入${page}关键字`}/></label><label>账号状态<select value={status} onChange={e=>setStatus(e.target.value)}><option>全部</option><option>启用</option><option>停用</option></select></label><button className="blue">⌕ 查询</button><button className="gold" onClick={()=>{setQuery("");setStatus("全部")}}>↻ 重置</button><button className="green" onClick={()=>setModal(true)}>＋新增</button></div>
 <div className="list-head"><h3>{page}列表</h3><span>共 {shown.length} 条</span></div><div className="table-scroll"><table><thead><tr><th>名称 / 账号</th><th>显示名称</th><th>类型 / 角色</th><th>负责人 / 岗位</th><th>更新时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.display}</td><td><em>{r.category}</em></td><td>{r.owner}</td><td>{r.updated}</td><td><button className={"switch "+(r.status?"on":"")} onClick={()=>toggle(r)}><i/></button></td><td><button className="link">编辑</button><button className="danger" onClick={()=>remove(r.id)}>删除</button><button className="link">详情</button></td></tr>)}</tbody></table>{!shown.length&&<div className="no-data">◇ 暂无数据</div>}</div><footer className="pager"><span>共 {shown.length} 条</span><select><option>10条/页</option></select><button disabled>‹</button><b>1</b><button disabled>›</button><span>前往　<input value="1" readOnly/>　页</span></footer></section></section>
 {modal&&<div className="modal-mask" role="dialog" aria-label={`新增${page}`}><form className="modal" onSubmit={add}><header><h2>新增{page}</h2><button type="button" onClick={()=>setModal(false)}>×</button></header><label>* 英文名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="请输入英文名称"/></label><label>* 中文名称<input value={display} onChange={e=>setDisplay(e.target.value)} placeholder="请输入中文名称"/></label><div className="form-grid"><label>类型<select><option>{moduleName}</option></select></label><label>状态<select><option>正常</option><option>停用</option></select></label></div><label>简介<textarea placeholder="请输入内容"/></label><footer><button type="button" onClick={()=>setModal(false)}>取 消</button><button className="blue">确 定</button></footer></form></div>}
 </main>
}
